
---

# 2) GitHub Actions: `.github/workflows/ci.yml`

```yaml
name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build & Test
        run: ./gradlew clean build --no-daemon
